### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by ThisIsntLeo** [rA9stuff/LeetDown#118]
**Describe the bug**
When I attempt to open LeetDown, it immediately crashes.

**What is your macOS version?**
macOS Big Sur 11.7

**What is the device you're trying to downgrade?**
iPad Air 1 (WiFi)

**What is the LeetDown version you're using?**
2.2

![Screen Shot 2022-09-26 at 19 58 59](https://user-images.githubusercontent.com/96735005/192271812-87961c54-ae0a-4f8f-9823-90d2ec4ac414.png)
[LDLog.txt](https://github.com/rA9stuff/LeetDown/files/9646014/LDLog.txt)

**Comment by rA9stuff** [comment]
Copy it to your `/Applications` folder.

**Comment by ThisIsntLeo** [comment]
> Copy it to your `/Applications` folder.

worked thanks
