### ISSUE TITLE
Restore struck at red screen

### ISSUE THREAD

**Issue by sabhashanki** [rA9stuff/LeetDown#12]
I have 2 iphone 5s.  I can able to downgrade my first phone without any issues. But the second one hangs at red screen and pops out error "restore failed press the killswitch to try again. I have tried for nearly 50times and still getting the same issue. 

Have tried with different versions different cables and different ports but no use. 

Somebody help pls ?

**Comment by rA9stuff** [comment]
Please run leetdown from terminal using the command below and send the output here

/Applications/leetdown.app/Contents/MacOS/leetdown

**Comment by lukapil** [comment]
Same on iPad Air 
![CA7CCEAB-0EA4-469D-9402-092403864343](https://user-images.githubusercontent.com/62713900/98685886-35bbc080-2368-11eb-8253-1963559ff316.jpeg)

**Comment by lukapil** [comment]
I solve the problem with “sudo killall  -STOP -c usbd “ . Thanks anyway. In the first the device when connected continuos beeping sound of connect and disconnect in normal mode. I hope this help .

**Comment by ransom-party** [comment]
Tried to downgrade from 12.4.9 which is not officially supported, got error -45
![Screen Shot 2020-11-14 at 05 49 15](https://user-images.githubusercontent.com/74448150/99142867-1ecbe580-266a-11eb-83c8-ebc63d3509f6.png)

**Comment by rA9stuff** [comment]
@ransom-party It should work fine after you relaunch it since it deletes the created files at launch. Please try again.

**Comment by jkrosado** [comment]
i have a similar problem, but instead of saying “restore failed” it claims to have successfully finished
no idea what it is
