### ISSUE TITLE
Failed on ipad mini 2 with parsing firmware.json failed

### ISSUE THREAD

**Issue by xixixihaha** [rA9stuff/LeetDown#121]
**Describe the bug**
Tried to downgrade ipad mini 2. But failed. 
Also tried to downgrade in terminal with command "sudo /Applications/LeetDown.app/Contents/MacOS/LeetDown"
It showed the following info
[TSSC] opening firmwares.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[Error] failed to download file from=https://api.ipsw.me/v2.1/firmwares.json/condensed to=/tmp/firmwares.json CURLcode=28
futurerestore: failed with exception:
[exception]:
what=[TSSC] parsing firmware.json failed

code=75431953
line=1151
file=futurerestore.cpp
commit count=194:
commit sha  =0ab9df3209ee599f581532d05d331e6abe0f53f3

**What is your macOS version?**
e.g. macOS 10.15.7 on intel silicon

**What is the device you're trying to downgrade?**
iPad2 mini

**What is the LeetDown version you're using?**
Tried 2.0.1a 2.1 2.2, all failed.

**Enable debugging in LeetDown's settings and copy and paste LDLog.txt here. **

**Additional info (optional)**
2.0.1a  there is restore firmware alert on ipad 2 mini screen.
2.1 2.2 there is just black screen on ipad 2 mini screen

**Comment by rA9stuff** [comment]
Restore to latest iOS version then try again.

**Comment by xixixihaha** [comment]
> Restore to latest iOS version then try again.

Looks like there are OS requirements.
I've tried another Mac with Monterey.
V2.0.1a still failed to restore to 10.3.3. But with V2.2, it restored successfully.
