### ISSUE TITLE
iPadmini2降级失败

### ISSUE THREAD

**Issue by ACCEEjh** [rA9stuff/LeetDown#123]
**Describe the bug**

**What is your macOS version?**
e.g. macOS 11.1
Macos 10.15
**What is the device you're trying to downgrade?**
e.g. iPhone 5s
iPadmini2
**What is the LeetDown version you're using?**
e.g. 2.1
v2.2
**Enable debugging in LeetDown's settings and copy and paste LDLog.txt here. **

**Additional info (optional)**
利用漏洞失败 @rA9stuff # # #82 # # #82 #

**Comment by rA9stuff** [comment]
I don't even know what to say other than :frcoal:
