### ISSUE TITLE
iPad Air from 12.5.7 to iOS 10.3.3 downgrade not successful 

### ISSUE THREAD

**Issue by gianry** [rA9stuff/LeetDown#127]
I tried to downgrade with leetDown tool without success. 

after saved blob to file the iPad reboot and then receive the following message ...

[+]  Successfully booted /var/folders/0h/glyrl91j5gs7hnllwb124tmr0000gn/T/iPSW/Firmware/DFU/iBSS.ipad4.RELEASE.im4p
[+]  5 second cooldown, re-plug now if needed on Apple Silicon
[+]  Sending /var/folders/0h/glyrl91j5gs7hnllwb124tmr0000gn/T/iPSW/Firmware/DFU/iBEC.ipad4.RELEASE.im4p
[+]  Failed to connect to device, reconnect the USB cable to your mac to try again

thanks for your support

**Comment by rA9stuff** [comment]
Restore your iPad to iOS 12.5.7 with an iPSW and try again

**Comment by gianry** [comment]
done ! and succesfully downgraded
