### ISSUE TITLE
leetdown is damaged and can't be opened

### ISSUE THREAD

**Issue by Censorme** [rA9stuff/LeetDown#13]
I have a mac book pro running OSX  High Sierra and when I try to run this software I get the message that it is damaged and to throw it in the trash. I have tried to run it inside the Applications folder and from the extracted state and both give me this error, any Ideas why?

**Comment by ConsoleLogLuke** [comment]
Run this in Terminal and try again:
```bash
xattr -cr /Applications/leetdown.app
```

**Comment by Censorme** [comment]
Thank You Luke, Worked like a charm.

**Comment by ConsoleLogLuke** [comment]
Glad to hear that! I'll close the issue.
