### ISSUE TITLE
iPad mini 3 "unsupported device" 

### ISSUE THREAD

**Issue by Pick96** [rA9stuff/LeetDown#14]
I try with an iPad mini 3 and error say "unsupported device" , any idea ?

**Comment by ConsoleLogLuke** [comment]
As the error suggests, LeetDown doesn't support the iPad mini 3. The Mini 3 unfortunately doesn't have iOS 10.3.3 OTA signed so it's impossible to add support at the moment.

**Comment by Pick96** [comment]
In the future will have support?

**Comment by ConsoleLogLuke** [comment]
Unless Apple starts OTA signing iOS 10.3.3 for the Mini 3 (which they almost definitely won't), it won't be possible to add support for it using the method that LeetDown uses. So I can pretty confidently say that it won't have support for it in the future, unless the developer decides to add other downgrade methods.
