### ISSUE TITLE
on Big Sur

### ISSUE THREAD

**Issue by mdleung** [rA9stuff/LeetDown#21]
/Applications/leetdown.app/Contents/MacOS/leetdown ; exit;
rm: no_device: No such file or directory
rm: no_dfu: No such file or directory
rm: no_dfu: No such file or directory
rm: no_device: No such file or directory
rm: libusb_missing: No such file or directory
rm: *.im4p: No such file or directory
rm: *.stock: No such file or directory
rm: *.patched: No such file or directory
rm: *.shsh: No such file or directory
rm: *.shsh2: No such file or directory
rm: *.bbfw: No such file or directory
rm: no_ipsw: No such file or directory
rm: no_dfu: No such file or directory
rm: no_device: No such file or directory
Your current ApNonce is 778282f0cf6e5234446d88ebc5dcfde81f415b57
7b5c9d9ca50
Your device is an iPad4,4
Your boardconfig is j85ap
rm: no_device: No such file or directory
rm: no_dfu: No such file or directory
rm: libusb_missing: No such file or directory
libusb exists.
No matching processes belonging to you were found
No matching processes belonging to you were found
/Applications/leetdown.app/Contents/rsr/pwnedDFU.sh: line 2: 47840 Alarm clock: 14         perl -e 'alarm shift; exec
@ARGV
' "$@"
No matching processes belonging to you were found
No matching processes belonging to you were found
^Z

**Comment by kovuba** [comment]
I have the same problem on ip5s, exactly same log
