### ISSUE TITLE
Restore failed. Press the killswitch to try again

### ISSUE THREAD

**Issue by lewozgo** [rA9stuff/LeetDown#23]
Hello there! I tried to downgrade my iPhone5S (running IOS 12.4.9) to 10.3.3 but it keeps saying that "Restore failed. Press the killswitch to try again". Any solution?

**Comment by decunited** [comment]
Hi there! Im certainly no expert but i was only able to downgrade my iPhone 5s with this tool but not on my iPad mini 2. For my iPad, I used the vieux downgrade tool which is run from terminal. You also need to install python 3, which version 3.75 worked for me, as the latest one would crash. I hope this helps!

Here is more info on it.
https://github.com/MatthewPierson/Vieux

**Comment by lsin93** [comment]
Hi @decunited , appreciate if you could guide me with a video. I tried all the steps given in the link but still couldn't downgrade my ipad mini 2.
