### ISSUE TITLE
Cant install libusb in mojave

### ISSUE THREAD

**Issue by Shazin157** [rA9stuff/LeetDown#25]
Hello
    Need some help,i cant install libusb its saying failed to install libusb
Also i am using a vm,can anyone help.me

**Comment by Shazin157** [comment]
Hey please help me guys

**Comment by abudi2412** [comment]
Hey,

Which LeetDown Version are you using?

**Comment by MountainDrew** [comment]
I have this problem too im using catalina and im using leetdown version 1.0.3

**Comment by MountainDrew** [comment]
never mind

**Comment by MountainDrew** [comment]
its fixed

**Comment by z3r0c00l-2k** [comment]
How did you fixed it?

**Comment by z3r0c00l-2k** [comment]
@MountainDrew how did you fixed it?
