### ISSUE TITLE
always stuck on "restoring failed"

### ISSUE THREAD

**Issue by xtreme1608** [rA9stuff/LeetDown#26]
i try numerous time and still restoring failed, why?

**Comment by xtreme1608** [comment]
i'm on iphone 5s ios 12.4.9. iphone 6,2 code

**Comment by stonexing** [comment]
I got the same error with you.
And at that time my iPhone 5s got red screen.
the downgrade not success

**Comment by stonexing** [comment]
After I run
`brew install libusb`
I success downgrade two my iPhone 5s from 12.5.2 to 10.3.3 both
