### ISSUE TITLE
iPhone 5s pwnDFU error

### ISSUE THREAD

**Issue by Michael2987** [rA9stuff/LeetDown#27]
I've been trying to get my iPhone 6,1 in pwnDFU for the last 3 hours 

I have a 2009 MacBook running Mac OS Mojave dosdude1's patcher 

Help

**Comment by applemert** [comment]
I have the same Problem. Have you found a solution in the meantime?

**Comment by MountainDrew** [comment]
hold the home button and power button for at least 10 seconds then let go of the power button but continue holding the home button until it conects to your mac

**Comment by jkrosado** [comment]
> hold the home button and power button for at least 10 seconds then let go of the power button but continue holding the home button until it conects to your mac

not what OP is talking about

**Comment by Michael2987** [comment]
i fixed it after lots of info and testing i now have a Early-2015 MacBook Pro with Mojave 10.14.6 and pwndfu works 100% don't use older usb ports no matter what MacOS you are running, iPwnder or PwnDFU wont work on older usb interfaces i've narrowed it down sort of to minimum Mac machine Late-2012 or later 

hackontosh's do work if the PC was made in 2014 or 2015 or higher
