### ISSUE TITLE
Device exit a DFU mode

### ISSUE THREAD

**Issue by malovoy** [rA9stuff/LeetDown#29]
my iPad Air (iPad4,2) exit a DFU after i hit "pwnedDFU" button. I use MacBook Air (M1, 2020) 

<img width="682" alt="Снимок экрана 2021-01-12 в 19 35 55" src="https://user-images.githubusercontent.com/77404474/104484407-53144180-55da-11eb-8477-61f3070f1e5a.png">

**Comment by malovoy** [comment]
have to erase mac and now, after install required tool, app doesn't see the ipad in dfu mode

**Comment by malovoy** [comment]
after install rosetta 2 leetdown recognize device, but libusb is failing install

**Comment by rA9stuff** [comment]
I don’t know how libusb works on M1 macs. Can you try running ``brew install libusb``
