### ISSUE TITLE
leetdown

### ISSUE THREAD

**Issue by 2escustomservices** [rA9stuff/LeetDown#3]
won't open said damaged

**Comment by mtomi95** [comment]
_Q: How to fix “this app is damaged and can't be opened” error?
• Launch Terminal app from /Applications/Utilities folder
• Copy and paste the command below to Terminal after you have copied LeetDown to your Applications folder
"xattr -cr /Applications/leetdown.app"
• Press enter
• Done! _

**Comment by 2escustomservices** [comment]
Thank you I was only putting one t lol
