### ISSUE TITLE
IPad Air 4,1 not working

### ISSUE THREAD

**Issue by Sdwok** [rA9stuff/LeetDown#32]
I’ve tried to downgrade my iPad Air multiple times and it says that it finished but still boots into iOS 12. Using 15 inch retina MacBook Pro late 2013 on macOS Big Sur

**Comment by decunited** [comment]
Hi there! Im certainly no expert but i was only able to downgrade my iPhone 5s with this tool but not on my iPad mini 2. For my iPad, I used the vieux downgrade tool which is run from terminal. You also need to install python 3, which version 3.75 worked for me, as the latest one would crash. I hope this helps!

Here is more info on it.
https://github.com/MatthewPierson/Vieux
