### ISSUE TITLE
iphone5s \ leetdown v1.03. restore failed,press the kill switch to try again

### ISSUE THREAD

**Issue by Lesuit** [rA9stuff/LeetDown#35]
MBP2019 BIG SUR,OSX 11.2.1
rm: no_device: No such file or directory
rm: no_dfu: No such file or directory
rm: no_dfu: No such file or directory
rm: no_device: No such file or directory
rm: libusb_missing: No such file or directory
rm: *.im4p: No such file or directory
rm: *.stock: No such file or directory
rm: *.patched: No such file or directory
rm: *.shsh: No such file or directory
rm: *.shsh2: No such file or directory
rm: *.bbfw: No such file or directory
rm: no_ipsw: No such file or directory
rm: no_dfu: No such file or directory
rm: no_device: No such file or directory
Your current ApNonce is 6e21a9166d7ecf1d96213b8dcfe19096b102a902
43649599330
Your device is an iPhone6,1
Your boardconfig is n51ap
rm: no_device: No such file or directory
rm: no_dfu: No such file or directory
rm: libusb_missing: No such file or directory
libusb exists.
No matching processes were found
No matching processes were found
No matching processes were found
Device is already in pwnedDFU
No matching processes were found
Your current ApNonce is 6e21a9166d7ecf1d96213b8dcfe19096b102a902
43649599330
Your device is an iPhone6,1
Your boardconfig is n51ap
Version: c0b554e83f54d39d90cac9791160bf2ccb062aed - 355
[TSSC] manually specified ECID to use, parsed "43649599330" to dec:43649599330 hex:a29b80762
[TSSC] manually specified ApNonce to use, parsed "6e21a9166d7ecf1d96213b8dcfe19096b102a902" to hex:6e21a9166d7ecf1d96213b8dcfe19096b102a902
[TSSC] opening BM/iPhone6,1.plist
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for update installing
[Error] [TSSR] Error: could not get id0 for installType=Update
[WARNING] [TSSR] faild to build tssrequest for alternative installType
[TSSR] User specified not to request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=128, message=An internal error occurred.)
Saved signing tickets!

iOS 10.3.3 for device iPhone6,1 IS being signed!
Your current ApNonce is 6e21a9166d7ecf1d96213b8dcfe19096b102a902
43649599330
Your device is an iPhone6,1
Your boardconfig is n51ap
Archive:  ../stock.ipsw
  inflating: 058-74917-062.dmg       
  inflating: ._058-74917-062.dmg     
  inflating: 058-74940-063.dmg       
  inflating: 058-75381-062.dmg       
  inflating: BuildManifest.plist     
   creating: Firmware/
   creating: Firmware/all_flash/
  inflating: Firmware/all_flash/applelogo@2x~iphone.s5l8960x.im4p  
  inflating: Firmware/all_flash/applelogo@2x~iphone.s5l8960x.im4p.plist  
  inflating: Firmware/all_flash/applelogo@2x~iphone.s8000.im4p  
  inflating: Firmware/all_flash/applelogo@2x~iphone.s8000.im4p.plist  
  inflating: Firmware/all_flash/applelogo@2x~iphone.s8003.im4p  
  inflating: Firmware/all_flash/applelogo@2x~iphone.s8003.im4p.plist  
  inflating: Firmware/all_flash/batterycharging0@2x~iphone.s5l8960x.im4p  
  inflating: Firmware/all_flash/batterycharging0@2x~iphone.s5l8960x.im4p.plist  
  inflating: Firmware/all_flash/batterycharging0@2x~iphone.s8000.im4p  
  inflating: Firmware/all_flash/batterycharging0@2x~iphone.s8000.im4p.plist  
  inflating: Firmware/all_flash/batterycharging0@2x~iphone.s8003.im4p  
  inflating: Firmware/all_flash/batterycharging0@2x~iphone.s8003.im4p.plist  
  inflating: Firmware/all_flash/batterycharging1@2x~iphone.s5l8960x.im4p  
  inflating: Firmware/all_flash/batterycharging1@2x~iphone.s5l8960x.im4p.plist  
  inflating: Firmware/all_flash/batterycharging1@2x~iphone.s8000.im4p  
  inflating: Firmware/all_flash/batterycharging1@2x~iphone.s8000.im4p.plist  
  inflating: Firmware/all_flash/batterycharging1@2x~iphone.s8003.im4p  
  inflating: Firmware/all_flash/batterycharging1@2x~iphone.s8003.im4p.plist  
  inflating: Firmware/all_flash/batteryfull@2x~iphone.s5l8960x.im4p  
  inflating: Firmware/all_flash/batteryfull@2x~iphone.s5l8960x.im4p.plist  
  inflating: Firmware/all_flash/batteryfull@2x~iphone.s8000.im4p  
  inflating: Firmware/all_flash/batteryfull@2x~iphone.s8000.im4p.plist  
  inflating: Firmware/all_flash/batteryfull@2x~iphone.s8003.im4p  
  inflating: Firmware/all_flash/batteryfull@2x~iphone.s8003.im4p.plist  
  inflating: Firmware/all_flash/batterylow0@2x~iphone.s5l8960x.im4p  
  inflating: Firmware/all_flash/batterylow0@2x~iphone.s5l8960x.im4p.plist  
  inflating: Firmware/all_flash/batterylow0@2x~iphone.s8000.im4p  
  inflating: Firmware/all_flash/batterylow0@2x~iphone.s8000.im4p.plist  
  inflating: Firmware/all_flash/batterylow0@2x~iphone.s8003.im4p  
  inflating: Firmware/all_flash/batterylow0@2x~iphone.s8003.im4p.plist  
  inflating: Firmware/all_flash/batterylow1@2x~iphone.s5l8960x.im4p  
  inflating: Firmware/all_flash/batterylow1@2x~iphone.s5l8960x.im4p.plist  
  inflating: Firmware/all_flash/batterylow1@2x~iphone.s8000.im4p  
  inflating: Firmware/all_flash/batterylow1@2x~iphone.s8000.im4p.plist  
  inflating: Firmware/all_flash/batterylow1@2x~iphone.s8003.im4p  
  inflating: Firmware/all_flash/batterylow1@2x~iphone.s8003.im4p.plist  
  inflating: Firmware/all_flash/DeviceTree.n51ap.im4p  
  inflating: Firmware/all_flash/DeviceTree.n51ap.im4p.plist  
  inflating: Firmware/all_flash/DeviceTree.n53ap.im4p  
  inflating: Firmware/all_flash/DeviceTree.n53ap.im4p.plist  
  inflating: Firmware/all_flash/DeviceTree.n69ap.im4p  
  inflating: Firmware/all_flash/DeviceTree.n69ap.im4p.plist  
  inflating: Firmware/all_flash/DeviceTree.n69uap.im4p  
  inflating: Firmware/all_flash/DeviceTree.n69uap.im4p.plist  
  inflating: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s5l8960x.im4p  
  inflating: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s5l8960x.im4p.plist  
  inflating: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8000.im4p  
  inflating: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8000.im4p.plist  
  inflating: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8003.im4p  
  inflating: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8003.im4p.plist  
  inflating: Firmware/all_flash/iBoot.iphone6.RELEASE.im4p  
  inflating: Firmware/all_flash/iBoot.iphone6.RELEASE.im4p.plist  
  inflating: Firmware/all_flash/iBoot.n69.RELEASE.im4p  
  inflating: Firmware/all_flash/iBoot.n69.RELEASE.im4p.plist  
  inflating: Firmware/all_flash/iBoot.n69u.RELEASE.im4p  
  inflating: Firmware/all_flash/iBoot.n69u.RELEASE.im4p.plist  
  inflating: Firmware/all_flash/LLB.iphone6.RELEASE.im4p  
  inflating: Firmware/all_flash/LLB.iphone6.RELEASE.im4p.plist  
  inflating: Firmware/all_flash/LLB.n69.RELEASE.im4p  
  inflating: Firmware/all_flash/LLB.n69.RELEASE.im4p.plist  
  inflating: Firmware/all_flash/LLB.n69u.RELEASE.im4p  
  inflating: Firmware/all_flash/LLB.n69u.RELEASE.im4p.plist  
  inflating: Firmware/all_flash/recoverymode@1136~iphone-lightning.s5l8960x.im4p  
  inflating: Firmware/all_flash/recoverymode@1136~iphone-lightning.s5l8960x.im4p.plist  
  inflating: Firmware/all_flash/recoverymode@1136~iphone-lightning.s8000.im4p  
  inflating: Firmware/all_flash/recoverymode@1136~iphone-lightning.s8000.im4p.plist  
  inflating: Firmware/all_flash/recoverymode@1136~iphone-lightning.s8003.im4p  
  inflating: Firmware/all_flash/recoverymode@1136~iphone-lightning.s8003.im4p.plist  
  inflating: Firmware/all_flash/sep-firmware.n51.RELEASE.im4p  
  inflating: Firmware/all_flash/sep-firmware.n51.RELEASE.im4p.plist  
  inflating: Firmware/all_flash/sep-firmware.n53.RELEASE.im4p  
  inflating: Firmware/all_flash/sep-firmware.n53.RELEASE.im4p.plist  
  inflating: Firmware/all_flash/sep-firmware.n69.RELEASE.im4p  
  inflating: Firmware/all_flash/sep-firmware.n69.RELEASE.im4p.plist  
  inflating: Firmware/all_flash/sep-firmware.n69u.RELEASE.im4p  
  inflating: Firmware/all_flash/sep-firmware.n69u.RELEASE.im4p.plist  
  inflating: Firmware/aopfw.im4p     
   creating: Firmware/dfu/
  inflating: Firmware/dfu/iBEC.iphone6.RELEASE.im4p  
  inflating: Firmware/dfu/iBEC.iphone6.RELEASE.im4p.plist  
  inflating: Firmware/dfu/iBEC.n69.RELEASE.im4p  
  inflating: Firmware/dfu/iBEC.n69.RELEASE.im4p.plist  
  inflating: Firmware/dfu/iBEC.n69u.RELEASE.im4p  
  inflating: Firmware/dfu/iBEC.n69u.RELEASE.im4p.plist  
  inflating: Firmware/dfu/iBSS.iphone6.RELEASE.im4p  
  inflating: Firmware/dfu/iBSS.iphone6.RELEASE.im4p.plist  
  inflating: Firmware/dfu/iBSS.n69.RELEASE.im4p  
  inflating: Firmware/dfu/iBSS.n69.RELEASE.im4p.plist  
  inflating: Firmware/dfu/iBSS.n69u.RELEASE.im4p  
  inflating: Firmware/dfu/iBSS.n69u.RELEASE.im4p.plist  
  inflating: Firmware/Mav10-5.62.00.Release.bbfw  
  inflating: Firmware/Mav10-5.62.00.Release.plist  
  inflating: Firmware/Mav7Mav8-7.60.00.Release.bbfw  
  inflating: Firmware/Mav7Mav8-7.60.00.Release.plist  
   creating: Firmware/usr/
   creating: Firmware/usr/local/
   creating: Firmware/usr/local/standalone/
  inflating: kernelcache.release.iphone6  
  inflating: kernelcache.release.iphone8b  
  inflating: Restore.plist           
  adding: 058-74917-062.dmg (deflated 1%)
  adding: 058-74940-063.dmg (deflated 17%)
  adding: 058-75381-062.dmg (deflated 17%)
  adding: BuildManifest.plist (deflated 95%)
  adding: Firmware/ (stored 0%)
  adding: Firmware/aopfw.im4p (deflated 45%)
  adding: Firmware/usr/ (stored 0%)
  adding: Firmware/usr/local/ (stored 0%)
  adding: Firmware/usr/local/standalone/ (stored 0%)
  adding: Firmware/dfu/ (stored 0%)
  adding: Firmware/dfu/iBEC.n69.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/dfu/iBSS.n69u.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/dfu/iBSS.iphone6.RELEASE.im4p (deflated 51%)
  adding: Firmware/dfu/iBEC.n69.RELEASE.im4p (deflated 0%)
  adding: Firmware/dfu/iBEC.n69u.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/dfu/iBEC.n69u.RELEASE.im4p (deflated 0%)
  adding: Firmware/dfu/iBSS.iphone6.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/dfu/iBEC.iphone6.RELEASE.im4p (deflated 49%)
  adding: Firmware/dfu/iBSS.n69.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/dfu/iBEC.iphone6.RELEASE.im4p.plist (deflated 28%)
  adding: Firmware/dfu/iBSS.n69u.RELEASE.im4p (deflated 0%)
  adding: Firmware/dfu/iBSS.n69.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/ (stored 0%)
  adding: Firmware/all_flash/DeviceTree.n51ap.im4p.plist (deflated 37%)
  adding: Firmware/all_flash/batterycharging0@2x~iphone.s8000.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8000.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/sep-firmware.n51.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/iBoot.n69u.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/sep-firmware.n51.RELEASE.im4p.plist (deflated 37%)
  adding: Firmware/all_flash/LLB.n69.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/batterylow0@2x~iphone.s5l8960x.im4p (deflated 69%)
  adding: Firmware/all_flash/applelogo@2x~iphone.s8000.im4p.plist (deflated 38%)
  adding: Firmware/all_flash/batterylow0@2x~iphone.s8000.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batteryfull@2x~iphone.s8003.im4p (deflated 77%)
  adding: Firmware/all_flash/batteryfull@2x~iphone.s8003.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/recoverymode@1136~iphone-lightning.s5l8960x.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8000.im4p (deflated 13%)
  adding: Firmware/all_flash/sep-firmware.n69u.RELEASE.im4p.plist (deflated 37%)
  adding: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s5l8960x.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterycharging0@2x~iphone.s8003.im4p (deflated 20%)
  adding: Firmware/all_flash/batteryfull@2x~iphone.s5l8960x.im4p (deflated 77%)
  adding: Firmware/all_flash/applelogo@2x~iphone.s5l8960x.im4p (deflated 9%)
  adding: Firmware/all_flash/batterylow0@2x~iphone.s8000.im4p (deflated 69%)
  adding: Firmware/all_flash/applelogo@2x~iphone.s8000.im4p (deflated 9%)
  adding: Firmware/all_flash/recoverymode@1136~iphone-lightning.s8000.im4p (deflated 72%)
  adding: Firmware/all_flash/applelogo@2x~iphone.s5l8960x.im4p.plist (deflated 38%)
  adding: Firmware/all_flash/batterycharging0@2x~iphone.s5l8960x.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batteryfull@2x~iphone.s5l8960x.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s5l8960x.im4p (deflated 13%)
  adding: Firmware/all_flash/sep-firmware.n69.RELEASE.im4p.plist (deflated 37%)
  adding: Firmware/all_flash/DeviceTree.n69uap.im4p.plist (deflated 37%)
  adding: Firmware/all_flash/LLB.iphone6.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/DeviceTree.n69uap.im4p (deflated 82%)
  adding: Firmware/all_flash/recoverymode@1136~iphone-lightning.s8000.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterycharging1@2x~iphone.s8000.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterycharging1@2x~iphone.s5l8960x.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterylow1@2x~iphone.s8000.im4p (deflated 12%)
  adding: Firmware/all_flash/recoverymode@1136~iphone-lightning.s5l8960x.im4p (deflated 72%)
  adding: Firmware/all_flash/LLB.n69u.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterylow1@2x~iphone.s8000.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/LLB.n69.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/LLB.iphone6.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/batterycharging1@2x~iphone.s5l8960x.im4p (deflated 12%)
  adding: Firmware/all_flash/iBoot.n69u.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterycharging1@2x~iphone.s8003.im4p (deflated 12%)
  adding: Firmware/all_flash/iBoot.iphone6.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterycharging1@2x~iphone.s8003.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterycharging1@2x~iphone.s8000.im4p (deflated 12%)
  adding: Firmware/all_flash/batterylow0@2x~iphone.s5l8960x.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/batterylow1@2x~iphone.s8003.im4p (deflated 12%)
  adding: Firmware/all_flash/batterylow1@2x~iphone.s8003.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/sep-firmware.n69.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/batterylow1@2x~iphone.s5l8960x.im4p (deflated 12%)
  adding: Firmware/all_flash/DeviceTree.n69ap.im4p.plist (deflated 37%)
  adding: Firmware/all_flash/iBoot.n69.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/recoverymode@1136~iphone-lightning.s8003.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/sep-firmware.n53.RELEASE.im4p.plist (deflated 37%)
  adding: Firmware/all_flash/batterylow0@2x~iphone.s8003.im4p (deflated 69%)
  adding: Firmware/all_flash/applelogo@2x~iphone.s8003.im4p (deflated 9%)
  adding: Firmware/all_flash/DeviceTree.n69ap.im4p (deflated 82%)
  adding: Firmware/all_flash/batterycharging0@2x~iphone.s5l8960x.im4p (deflated 20%)
  adding: Firmware/all_flash/recoverymode@1136~iphone-lightning.s8003.im4p (deflated 72%)
  adding: Firmware/all_flash/iBoot.n69.RELEASE.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/sep-firmware.n69u.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/batterylow1@2x~iphone.s5l8960x.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/DeviceTree.n53ap.im4p (deflated 83%)
  adding: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8003.im4p (deflated 13%)
  adding: Firmware/all_flash/batterycharging0@2x~iphone.s8000.im4p (deflated 20%)
  adding: Firmware/all_flash/DeviceTree.n53ap.im4p.plist (deflated 37%)
  adding: Firmware/all_flash/batteryfull@2x~iphone.s8000.im4p (deflated 77%)
  adding: Firmware/all_flash/batterycharging0@2x~iphone.s8003.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/iBoot.iphone6.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/glyphplugin@1136~iphone-lightning.s8003.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/sep-firmware.n53.RELEASE.im4p (deflated 0%)
  adding: Firmware/all_flash/batteryfull@2x~iphone.s8000.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/DeviceTree.n51ap.im4p (deflated 83%)
  adding: Firmware/all_flash/batterylow0@2x~iphone.s8003.im4p.plist (deflated 26%)
  adding: Firmware/all_flash/applelogo@2x~iphone.s8003.im4p.plist (deflated 38%)
  adding: Firmware/all_flash/LLB.n69u.RELEASE.im4p (deflated 0%)
  adding: Firmware/Mav10-5.62.00.Release.plist (deflated 23%)
  adding: Firmware/Mav7Mav8-7.60.00.Release.plist (deflated 29%)
  adding: Firmware/Mav10-5.62.00.Release.bbfw (deflated 0%)
  adding: Firmware/Mav7Mav8-7.60.00.Release.bbfw (deflated 0%)
  adding: Restore.plist (deflated 84%)
  adding: kernelcache.release.iphone6 (deflated 6%)
  adding: kernelcache.release.iphone8b (deflated 6%)
rm: it_worked: No such file or directory
rm: ipsw/: is a directory
Your current ApNonce is 6e21a9166d7ecf1d96213b8dcfe19096b102a902
43649599330
Your device is an iPhone6,1
Your boardconfig is n51ap
Version: 81b98e0425e17250cc83d5badaf9a8cc6399f481 - 245
Libipatcher version: 3159a387584e352f690cca859e013c3a4683f3e8 - 69
Odysseus support: yes
[INFO] 64-bit device detected
futurerestore init done
reading signing ticket shsh.shsh2 is done
Found device iPhone6,1 n51ap
[TSSC] opening BM/iPhone6,1.plist
[TSSR] User specified not to request a baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set SEP+baseband path and firmware
[WARNING] Failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] Using tsschecker's fallback BasebandGoldCertID. This might result in invalid baseband signing status information
[WARNING] Failed to read BasebandSerialNumber from device! Is it already in recovery?
[WARNING] Using tsschecker's fallback BasebandSerialNumber size. This might result in invalid baseband signing status information
[TSSC] opening BM/iPhone6,1.plist
[TSSR] User specified to request only a baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in DFU mode
[Error] unsupported device mode, please put device in recovery mode or normal mode
[Error] Fail code=-3
Failed with errorcode=-3
fail
rm: ipsw_create_err: No such file or directory
rm: libusb_missing: No such file or directory
rm: no_device: No such file or directory
rm: no_dfu: No such file or directory
rm: *.patched: No such file or directory
rm: *.shsh: No such file or directory

**Comment by Nutr1t07** [comment]
Same issue here. Any solution?

**Comment by rA9stuff** [comment]
Please try [version 2.0](https://github.com/rA9stuff/LeetDown/releases) and let me know if it works.

**Comment by Lesuit** [comment]
I tried V2.01 and it worked well:)
Much appreciated.
