### ISSUE TITLE
Failed to install libusb

### ISSUE THREAD

**Issue by dwread** [rA9stuff/LeetDown#36]
I tried to downgrade my iPad Air 1st Gen (iPad 4,1) to iOS 10.3.3 but as soon as I click downgrade It complains about libusb not installed and If I try to install it says 'failed to install libusb' Yes, I have tried Homebrew, It installs but Leetdown still doesn't detect libusb

This is on an M1 Macbook Pro running macOS 11.0 (Big Sur)

**Comment by MountainDrew** [comment]
maybe try downloading it here (fixed that issue for me) https://libusb.info/

**Comment by dwread** [comment]
How am I meant to install it? I have files but what do I do with them?

**Comment by dwread** [comment]
nvm the update got libusb working but there is another issue (not with the app)
