### ISSUE TITLE
dependency_install  跳过libusb failed

### ISSUE THREAD

**Issue by Continueder** [rA9stuff/LeetDown#38]
macos 11的情况下，打开dependency_install.sh,同时手工用终端执行里面的命令
执行完后，讲if 后的11改为12，让判断直接跳过，直接执行绕过libusb的安装

**Comment by rA9stuff** [comment]
Please use the version 1.0.4

**Comment by rA9stuff** [comment]
Fixed on [version 2.0](https://github.com/rA9stuff/LeetDown/releases)
