### ISSUE TITLE
my iPhone 5s exit DFU Mode and after enter in normal mode and nothing happened

### ISSUE THREAD

**Issue by davicordeirodcs** [rA9stuff/LeetDown#44]
I using MacOs High Sierra (**Hackintosh**)

**Comment by Itsme758** [comment]
Hello Mate, I was just attempting the restore and it didn't work, the device kept going back to ios after selecting pwnedDFU. I read on some older posts and noticed a user had success with the 1.0.3 version. 

Thats what I did deleted version 1.0.4 of leetdown and downloaded 1.0.3 and it WORKS!!!

**Comment by rA9stuff** [comment]
Fixed on the [Version 1.0.5](https://github.com/rA9stuff/LeetDown/releases/tag/1.0.5)

**Comment by Itsme758** [comment]
> Fixed on the [Version 1.0.5](https://github.com/rA9stuff/LeetDown/releases/tag/1.0.5)

Absolute Legend!
Restored using the 1.0.5 version. Works like a charm.
