### ISSUE TITLE
Support for 32-bit OTA downgrades to iOS 6.1.3 and 8.4.1

### ISSUE THREAD

**Issue by Grandboy46** [rA9stuff/LeetDown#48]
Hello,

Leetdown is the only GUI tool that supports OTA downgrades to 10.3.3 on A7. But there are also possible downgrades on 32-bit devices to 8.4.1 and 6.1.3 using the same method. Can you also support downgrades to 6.1.3 and 8.4.1 on supported devices?

**Comment by developerss** [comment]
u have to modify version plist from mnt1 6.1.3 then u can upgrade 8.4

**Comment by developerss** [comment]
this was the end of iphone no meid , so i deleted the comment , learned 60 percent 5s 12,5,3 locked now i can use call
