### ISSUE TITLE
Iphone 5s Can't stay in dfu mode because the proccess took too long

### ISSUE THREAD

**Issue by rthedaf** [rA9stuff/LeetDown#5]
The proccess (copying selected ipsw and creating custom ipsw) took longer than my dfu timout, it always rebooted to lock screen before restoring device. Is there some workaround to make proccess faster?

**Comment by rA9stuff** [comment]
AFAIK there’s no such thing as “DFU timeout”. Can you check the connection between Mac and the idevice? Also, make sure you hold power+home buttons for 10 seconds before letting go the power button.

**Comment by MountainDrew** [comment]
im having the same problem with my ipad mini 2

**Comment by Solomon-Wood** [comment]
I managed to do this on my iPad mini 2 one time, but every time I have tried afterwards it has failed. It seems that pwnDFU works, but nothing else has. 

OS: macOS Big Sur 11.1. I used BenSova's Patcher both times. Would that change reliability?
Thanks in advance.
