### ISSUE TITLE
dfu mode not working on iphone 5s

### ISSUE THREAD

**Issue by gwizdavies12** [rA9stuff/LeetDown#51]
when i try to run the command, it says that the iphone is in the wrong mode and that i need to put it into dfu mode even though it already is.

**Comment by estaf1001** [comment]
Be press power+home one about 10 sec. After it be loose power one and hold a home one 10 sec.

**Comment by rA9stuff** [comment]
Please try [version 2.0.1](https://github.com/rA9stuff/LeetDown/releases) and let me know if it works fine.
