### ISSUE TITLE
App crashing on startup with 'namespace codesigning code 0x1' error

### ISSUE THREAD

**Issue by byeCl0ud** [rA9stuff/LeetDown#52]
I can't launch any version of leetdown anymore, even the previously installed one, that worked fine month ago. I'm on Mojave and Big Sur, both are giving the same error. I tried removing from quarantine, didn't help.

**Comment by rA9stuff** [comment]
Please try the latest release.

**Comment by Joey0102** [comment]
I downloaded the lasted version. Besides warning me it will damage my computer, it shows that leetdown quit unexpectedly. This is killing me.

Termination Reason:    Namespace CODESIGNING, Code 0x1

**Comment by byeCl0ud** [comment]
It's working fine for me now. Thanks for solving this quickly.

**Comment by Eptin** [comment]
I’m also seeing Termination Reason: Namespace CODESIGNING, Code 0x1
on High Sierra with the latest binary (1.0.5)

**Comment by estaf1001** [comment]
1.0.5
Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

**Comment by rA9stuff** [comment]
Try doing `sudo codesign --force --deep --sign - /Applications/leetdown.app` while I try to identify the issue.

**Comment by rA9stuff** [comment]
Fixed on [version 2.0](https://github.com/rA9stuff/LeetDown/releases)
