### ISSUE TITLE
iPad4,4(12.5.4)   MacOS BigSur11.5 error

### ISSUE THREAD

**Issue by yimiaodaren** [rA9stuff/LeetDown#53]
rm: restore_failed: No such file or directory
rm: it_worked: No such file or directory
rm: ipsw/: is a directory
Your current ApNonce is b2416f5b563fa2e86bc513cea20067d2be691390
2f4ccd9dbd4
Your device is an iPad4,4
Your boardconfig is j85ap
blankfile upload
ibss upload
ibec upload
Version: 81b98e0425e17250cc83d5badaf9a8cc6399f481 - 245
Libipatcher version: 3159a387584e352f690cca859e013c3a4683f3e8 - 69
Odysseus support: yes
[INFO] 64-bit device detected
futurerestore init done
reading signing ticket shsh.shsh2 is done
Found device iPad4,4 j85ap
[TSSC] opening BM/iPad4,4.plist
WARNING: Unable to find BbChipID node
[TSSR] User specified not to request a baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received

WARNING: user specified not to flash a baseband. This can make the restore fail if the device needs a baseband!
if you added this flag by mistake you can press CTRL-C now to cancel
continuing restore in 10 9 8 7 6 5 4 3 2 1 
Found device in DFU mode
[Error] unsupported device mode, please put device in recovery mode or normal mode
[Error] Fail code=-3
Failed with errorcode=-3
fail
rm: ipsw_create_err: No such file or directory
rm: libusb_missing: No such file or directory
rm: no_device: No such file or directory
rm: no_dfu: No such file or directory
rm: *.patched: No such file or directory
rm: *.shsh: No such file or directory
rm: *.bbfw: No such file or directory

**Comment by rA9stuff** [comment]
Please try [version 2.0](https://github.com/rA9stuff/LeetDown/releases) and let me know if it works.
