### ISSUE TITLE
iPadmini2 12.5.2restore failed

### ISSUE THREAD

**Issue by yehua2000** [rA9stuff/LeetDown#56]
[]
<img width="476" alt="屏幕快照 2021-07-04 下午10 24 17" src="https://user-images.githubusercontent.com/86919474/124388710-998b6300-dd16-11eb-9e95-a949c4d7f4d2.png">
restore failed

**Comment by PENG-OX** [comment]
You can try here #63

**Comment by rA9stuff** [comment]
Please try [version 2.0](https://github.com/rA9stuff/LeetDown/releases) and let me know if it works fine now.
