### ISSUE TITLE
gives an error [*] Unsupported device

### ISSUE THREAD

**Issue by motogon** [rA9stuff/LeetDown#57]
Hi 
ipad 3 mini wifi 

gives an error [*] Unsupported device

![изображение](https://user-images.githubusercontent.com/12997195/124392176-e6fad680-dcfc-11eb-8ec8-794d9136c821.png)

I am using version 1.0.5_v2

**Comment by rA9stuff** [comment]
iPad Mini 3 is not supported by LeetDown as it never shipped with 7.0.x which is the reason apple signs 10.3.3 as an OTA update.
