### ISSUE TITLE
This App is identified as a malicious program

### ISSUE THREAD

**Issue by RealYellowMan** [rA9stuff/LeetDown#59]
<img width="345" alt="Screen Shot 2021-07-05 at 10 55 05 AM" src="https://user-images.githubusercontent.com/86972008/124489906-7fd23600-dd7f-11eb-8a74-96548d795682.png">

**Comment by samirgcofficial** [comment]
Did you find any solutions yet ?

**Comment by rA9stuff** [comment]
Try doing sudo codesign --force --deep --sign - /Applications/leetdown.app while I try to identify the issue.
