### ISSUE TITLE
Is downgrading OFFLINE possible?

### ISSUE THREAD

**Issue by freeze-dolphin** [rA9stuff/LeetDown#61]
I have no Mac, so I installed a `Black Apple` to run `LeetDown`.
But one problem was that I had no idea to have access to the Internet (I cannot find out the correct WLAN Driver). I've spent so much time on this, and it's getting me annoyed. So I downgrading offline is important.

I've known that `LeetDown` needs to use the `git`, so may it be possible to downgrade my `iPhone 5s` after cloning the necessary repositories by using an Internet-connected computer and putting them into 'correct' location(s)?

**Comment by rA9stuff** [comment]
LeetDown needs an internet connection to downgrade as it requests different blobs from Apple's server to match the apnonces. So it's not possible to use it offline.
