### ISSUE TITLE
This app keeps crashing on macOS Catalina 

### ISSUE THREAD

**Issue by RealYellowMan** [rA9stuff/LeetDown#62]
<img width="426" alt="Screen Shot 2021-07-13 at 1 10 27 PM" src="https://user-images.githubusercontent.com/86972008/125496139-662962b0-9ecf-461f-8fda-ac050c105585.png">

**Comment by Ngoni-Sama** [comment]
![Screenshot 2021-07-21 at 18 44 03](https://user-images.githubusercontent.com/60420709/126526921-26ad2bc2-8bdc-4345-a278-b4d057584c70.png)

**Comment by rA9stuff** [comment]
Fixed on [version 2.0](https://github.com/rA9stuff/LeetDown/releases)
