### ISSUE TITLE
Create a temp directory to extract the IPSW into

### ISSUE THREAD

**Issue by m1stadev** [rA9stuff/LeetDown#65]
Won't need to worry about cleaning the extracted directory (also, it's better practice to, especially with something as large as an IPSW).

**Comment by rA9stuff** [comment]
Good advice, that would also fix `LeetDown` folder to be created in `/Applications` while using futurerestore.

**Comment by rA9stuff** [comment]
Added on [version 2.0.1](https://github.com/rA9stuff/LeetDown/releases/tag/2.0.1)

**Comment by CoderAquarius** [comment]
Thank you very much for allowing me to implement my 5S yesterday at once. It was implemented in a short time yesterday. I went from the 12.4.7 version to the 10.3.3 version, although I had a little bit of confusion about dFU and recovery mode Everything is fine thank you very much!

**Comment by BG6FCN** [comment]
Thank you

**Comment by BG6FCN** [comment]
I come from China most Chinese people are good and friendly!
