### ISSUE TITLE
V3.0 request for 6.1.3 and 8.4.1 OTA downgrades

### ISSUE THREAD

**Issue by Grandboy46** [rA9stuff/LeetDown#66]
Hello @rA9stuff,

I will have you a huge request for the next major update for Leetdown.

The major request that I will make is shortly support for 6.1.3 and 8.4.1 OTA Downgrade support for supported devices.

There is a TUI tool called [iOS-OTA-Downgrader](https://github.com/LukeZGD/iOS-OTA-Downgrader) which supports all 3 OTA downgrades (6.1.3 on S5L8940 devices, 8.4.1 on all A5, A5X, devices as well as iPhone 5 and iPad 4 and 10.3.3 on iPad Air, iPhone 5s and iPad mini 2). The problem is that TUI tool is not for beginners and for more advanced users only. Is it possible to make LeetDown support downgrades to 6.1.3 on S5L8940 and 8.4.1 on all A5, A5X, devices as well as iPhone 5 and iPad 4 so we have a GUI tool for all possible OTA Downgrades? This will make things more user-friendly. If not, can you create a new GUI tool for 6.1.3 and 8.4.1 OTA downgrdes on supported devices?

Sincerely,

**Comment by rA9stuff** [comment]
Hi **Grandboy46**,

I firstly want to apologize for not answering your [previous request](https://github.com/rA9stuff/LeetDown/issues/48), I was really busy with school work. Now, for your request, I understand the benefits of a GUI tool on inexperienced users, though, I don't have much experience on 32 bit devices. I'll take a look at how downgrading them works and after that I *may* work on a GUI tool for this purpose.
