### ISSUE TITLE
DFU helper has you hold Power + Home too long

### ISSUE THREAD

**Issue by bogotesr** [rA9stuff/LeetDown#67]
I'm not sure the exact timing but for me what always works is holding power + home till one second after the display goes off then releasing the power button. 

Not something I need help with just kinda trying to help make this tool best it can be.

**Comment by rA9stuff** [comment]
Hey thanks for the feedback! Holding the power + home button for less than 10 seconds might put you in soft DFU mode which is not compatible with iPwnder32.

**Comment by CobreDev** [comment]
For me, holding for more than 5-7 seconds makes it reboot into recovery mode

**Comment by rA9stuff** [comment]
@CobreDev make sure the cable is connected

**Comment by CobreDev** [comment]
It is, though I'll try a non-USB C cable later

**Comment by CobreDev** [comment]
Got it, that was the issueOn Jun 14, 2022, at 14:03, rA9 ***@***.***> wrote:﻿
Yeah you can’t enter normal DFU mode with a type-c cable.

**Comment by MrGlitchWasTaken** [comment]
> Yeah you can’t enter normal DFU mode with a type-c cable.

can you provide instructions on how to enter DFU mode if you already are in recovery mode? I goofed up.
