### ISSUE TITLE
Does this work on macos Panther?

### ISSUE THREAD

**Issue by Grandboy46** [rA9stuff/LeetDown#68]
In the readme, It states MacOS 10.3+ but I don’t think anything below High Sierra would work for Leetdown. Maybe it is MacOS 10.13+? I’m asking, is this tool actually works on MacOS 10.3 (Panther)? Or is it a mistake?

**Comment by rA9stuff** [comment]
I meant 10.13 😅. Thanks for letting me know I’ll update the readme now.
