### ISSUE TITLE
This isn't an issue. If leetdown it saying: Failed to restore device, try to reinstall it. It worked with me. If this isnt still working, then try it again or restart your mac

### ISSUE THREAD

**Issue by EpicXDavo** [rA9stuff/LeetDown#73]
Please Make Sure youre on Mac OS 11.2.3 Or Below. If it is saying "Failed to restore", then reinstall the app. Dont uninstall it, just install it asgain, and then if it asks, click "replace".

**Comment by EpicXDavo** [comment]
This worked for me. Thanks RA9Stuff for helping me fix the issue, please dont block me, this is just for people who are confused and are stuck.

**Comment by rA9stuff** [comment]
Not an issue, closing it.

**Comment by EpicXDavo** [comment]
Fine, but If people can't get it working still don't thank me
