### ISSUE TITLE
Ipad mini2 10.3.3

### ISSUE THREAD

**Issue by OwnerCM** [rA9stuff/LeetDown#74]
**Describe the bug**
notice：Waiting for the device to connect

**What is your macOS version?**
e.g. macOS 11.2.3

**What is the device you're trying to downgrade?**
e.g. iPad mini2

**What is the LeetDown version you're using?**
e.g. 10.3.3

**Comment by OwnerCM** [comment]
> Enter this command `/Applications/LeetDown.app/Contents/MacOS/LeetDown` to terminal then try downgrading your device again. After that copy and paste the terminal log here.

All I have is this picture
![fc3541a6cd32024ca8448b8754aec3d](https://user-images.githubusercontent.com/22722811/130216948-7a18f3fb-fa9c-4ca0-8a0f-1b322633f416.jpg)

**Comment by rA9stuff** [comment]
Well I can’t help you much without the log. If you’re running this on M1 mac, try unplugging  your device and plugging it back in when it says “Waiting for the device to connect”.

**Comment by OwnerCM** [comment]
> Well I can’t help you much without the log. If you’re running this on M1 mac, try unplugging your device and plugging it back in when it says “Waiting for the device to connect”.

![屏幕截图 2021-08-21 091826](https://user-images.githubusercontent.com/22722811/130306021-fe618dd5-9d59-468c-9aa6-8a03c9ce1490.png)

**Comment by OwnerCM** [comment]
Can VMware be used for downgrade?

**Comment by rA9stuff** [comment]
No
