### ISSUE TITLE
Why is the same A7 processor, but does not support mini3?

### ISSUE THREAD

**Issue by pcitme** [rA9stuff/LeetDown#90]
**Describe the bug**

**What is your macOS version?**
e.g. macOS 11.1

**What is the device you're trying to downgrade?**
e.g. iPhone 5s

**What is the LeetDown version you're using?**
e.g. 2.1

**Enable debugging in LeetDown's settings and copy and paste LDLog.txt here. **

**Additional info (optional)**

**Comment by jkrosado** [comment]
the reason 10.3.3 is signed is so that devices running iOS versions older than 7.1 can update iOS. the mini 3 didn't ship with iOS 7 and therefore doesn't have 10.3.3 signed.
